import Navbar from '@/components/Navbar'
import HomePage from '@/components/HomePage'
import Head from 'next/head'
import {auth} from "../firebase"
import { useEffect } from 'react'
import { useStateValue } from '../Context/StateProvider'
import { onAuthStateChanged } from 'firebase/auth'
import axios from "axios";


export default function Home({products}) {
  const [{basket},dispatch] = useStateValue();

  useEffect(() => {
    auth.onAuthStateChanged((authUser) => {
      console.log("The user is >>>", authUser)
      if(authUser){
        dispatch({
          type: "SET_USER",
          user: authUser
        })
      }
      else{
        dispatch({
          type: "SET_USER",
          user: null
        })
      }
    })
  },[])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar></Navbar>
        <HomePage products={products}></HomePage>
      </main>

     
    </>
  )
}

export async function getServerSideProps(){
    const {data} = await axios({
      url: "https://fakestoreapi.com/products",
      method: "GET",
    })

    return {
      props: {products: data}
    }
}
